### ISSUE TITLE
Add wugbot header to index.html

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#13]

**Comment by dwhieb** [comment]
I've added the wug vs. wugbot header image to [this folder](https://github.com/digitallinguistics/core/tree/master/website/img). Let's put that image at the top of the website, just like it is on the current wugbot.org.

The tag line beneath it should say, 'Digital linguistics for everyone' (maybe as an `<h1>`?)

**Comment by dwhieb** [comment]
And our home page already exists btw. It's the index.html file [here](https://github.com/digitallinguistics/core/tree/master/website). So this task is just a matter of editing that file, as well as the css in the css folder.

**Comment by wugology** [comment]
I think I did it. Still new to this push/pull stuff though.

**Comment by dwhieb** [comment]
Yeah your pull request came through! (It's badly named: You're requesting me to pull your changes in, so it's called a pull request. Seems like push request would have made more sense...)

I suggested a couple quick changes before merging your changes. They're in the comments on your pull request.
