### ISSUE TITLE
Add a nav bar to index.html

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#14]
Should be designed so that we can use it as a template on the rest of our pages

**Comment by dwhieb** [comment]
We need to add a navigation / menu to our wugbot.org home page (and any other pages that are up when this task is done). For now, it'll just have a few items:
* About Wugbot
* About Digital Linguistics (DLX)

The HTML for this will need to have a `<nav>` element ([read about it here](http://www.w3schools.com/TAgs/tag_nav.asp)), and inside of that an [unordered list](http://www.w3schools.com/html/html_lists.asp).

Where do we think the navigation should be displayed on the page? Very top? Right under the header image? On the left?

The next step is to add CSS rules to style the navigation menu the way we want it. This'll require some discussion (Thursday!).

**Comment by dwhieb** [comment]
@ShannonL Are you interested in tackling this one? You could do the HTML tonight and we can work together on the CSS tomorrow.

**Comment by ShannonL** [comment]
Unfortunately I am drowning in midterms and essays and I won't have time tonight :(.

**Comment by dwhieb** [comment]
Ick, that's never fun. :-/ Good luck getting it all done. And hey, if you've got any linguistics-related questions you could use some guidance on, let me know!

**Comment by dwhieb** [comment]
Commit de2920b83d54b7a04721f399e4006d4ac2c00149 in the dev version fixes this.
