### ISSUE TITLE
Create aboutWugbot.html and aboutDLX.html

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#16]
Add basic content from the DLX wiki, then delete that page from the DLX wiki

**Comment by wugology** [comment]
where is the dlx wiki?

**Comment by dwhieb** [comment]
We're gonna keep all of the documentation and project-level issues in the core repo, so you have to be there to get to it. It's hidden on the right side of the page.

**Comment by dwhieb** [comment]
https://github.com/digitallinguistics/core/wiki

**Comment by wugology** [comment]
Just to be totally clear: the aboutWugbot.html page should just be a single, new .html page using all the stuff from https://github.com/digitallinguistics/core/wiki, neatly organized maybe with headers and anchor tags and things. Once it's created, the wiki will be deleted?

I can definitely do the first part. Not sure how to delete the wiki pages. Also not sure how to assign myself to tasks. This is literally the first collaborative programming project I've ever done.

**Comment by dwhieb** [comment]
For the most part. The wiki will stick around to help us with project-internal documentation. So we don't want pages like 'Coding Practices' or 'Site Structure' to go on the website - that's just for us. But things like 'About Wugbot' and 'What is digital linguistics?' definitely belong on the website rather than the wiki.

In fact, for now let's just worry about the About Wugbot and the About Digital Linguistics parts, which you'll use [this page](https://github.com/digitallinguistics/core/wiki/Wugbot) and [this page](https://github.com/digitallinguistics/core/wiki/What-is-digital-linguistics%3F) from the wiki for. The content needs a lot of work, but don't worry about that for now.

**Comment by dwhieb** [comment]
You can delete wiki pages by clicking edit in the top right, then delete.

**Comment by dwhieb** [comment]
Within a task/issue, there should be a little zone in the right sidebar that says 'assign yourself'.

**Comment by wugology** [comment]
>The wiki will stick around to help us with project-internal documentation.

So do I delete it or not? I just want to be clear. And do I make one page (aboutWugbot.html) or two (aboutWugbot and aboutDLX)?

> The content needs a lot of work, but don't worry about that for now.

I can add a few things and make it flow nice and be readable to a layperson :)

> Within a task/issue, there should be a little zone in the right sidebar that says 'assign yourself'.

It says "Assignee" and below that "No one assigned" but nothing is clickable. Maybe I'm not part of the group? If you go to https://github.com/orgs/digitallinguistics/people it's just you and John.

**Comment by dwhieb** [comment]
Yeah I just realized you weren't even a member of the org! Just did that - you should have a notification about joining now, and the assigning thing should work now.

Don't delete the wiki, just the individual wiki pages you're moving to the website. And yeah, go ahead and make 2 pages. If you want to make a separate task for the second page, go for it.

**Comment by wugology** [comment]
This is what my sidebar looks like:

![screen shot 2015-02-02 at 7 58 12 pm](https://cloud.githubusercontent.com/assets/6477739/6014284/ec1a870c-ab15-11e4-8aab-34ec82a57962.png)

Still no clue how to assign myself to things, but I'm hereby declaring that I'm gonna do this one.

**Comment by dwhieb** [comment]
Ohhhh, so you have to click on the word Assignee, even though it doesn't look clickable. Then it pops up a little menu.

**Comment by dwhieb** [comment]
Nope wait, I lied. It's a permissions thing. Lemme see about changing it.

**Comment by dwhieb** [comment]
Ok I merged your changes from the first pull request - can you make another pull request?

**Comment by wugology** [comment]
@amundo I noticed you've edited the wikipage. Should I wait to make the about pages or go ahead? Was planning to tonight.

**Comment by wugology** [comment]
Actually... where did the entire core/website folder go? @amundo? @dwhieb?

**Comment by dwhieb** [comment]
It's movedǃ There's a new repo called digitallinguistics.github.io. Turns out GitHub has this fancy thing that allows you to do a live preview of whatever you're working on, but in order to do that, you have to setup a repo with that weird github.io name.

So what's really nice about this is, as you edit the files in that repo, you'll be able to automatically (plus maybe 60 seconds) see the live version of those most recent changes hereː
http://digitallinguistics.github.io/

**Comment by dwhieb** [comment]
Here's the repoː
https://github.com/digitallinguistics/digitallinguistics.github.io

**Comment by dwhieb** [comment]
Feel free to do the Wugbot page whenever you'd like. We'll continue adding to and changing the content after you move it.

**Comment by wugology** [comment]
I'm working on getting the about wiki into an html file using general layperson language (understandable to non-programmer linguists as well as interested community members). 

I'm having trouble with `<ul>` and `<li>` though. I can't get bullet points to show up. Also, whenever I do something like bold a single word, it makes it a new line. Idk what's wrong. This is what's happening:

![screen shot 2015-02-04 at 3 00 01 pm](https://cloud.githubusercontent.com/assets/6477739/6051615/8f75d550-ac7e-11e4-874a-d8202ca02bbc.png)


Also I feel weird editing the "master" style.css file! Like it looks hideous with full-screen width body, but I also feel like it's not my place to set body to 700px or whatever, and I also don't know if doing that will mess other things up (like mobile-readiness, or other pages ya'll are working on).

**Comment by dwhieb** [comment]
Go for whatever you think works! We can always change things back. Better to experiment I think.

I'm on my phone but I'll look more at this soon. And we'll do a code review tomorrow too.

**Comment by dwhieb** [comment]
The reason stuff is displaying funky is because of some rules already in the style sheet. These rules are called a 'CSS reset'. It strips away all the default styling that browsers apply automatically, so you start from bare bones. That includes the bullet points.

For navigation though, that's fine, bc we don't actually want bullet points, we want our nav to look like a menu. *Semantically* it's a list of links, but visually it looks like button or menus. Almost all nav menus are underlyingly lists without bullet points.

**Comment by dwhieb** [comment]
Are you using `<em>` tags for bold?

**Comment by dwhieb** [comment]
If so, the fix for the bold problem (I think) is to make sure somewhere in the style sheet the rule `display: inline;` gets applied to the `<em>` element. I can explain why that works later.

**Comment by dwhieb** [comment]
Huh, looks like that's not the problem. That rule is already in the style sheet.

**Comment by wugology** [comment]
So, I noticed that <em> and <b> weren't doing anything except adding extra lines. So I changed style.css to have `em{font-weight: bold;}` but it still does that.

Also, I'm not making a navigation list. I actually want a bullet point list so I can have a neat list of reasons why wugbot is awesome. I'm not touching navigation at all right now. So `ul {list-style-type: disc; padding-left: 50px; }` adds the indentation but doesn't add the disk. Is it because there's also `ol, ul {list-style: none; }` in style.css? What kinds of bullet points do we want site-wide?

**Comment by wugology** [comment]
I mean we could have a miniwug as a bullet point. @ShannonL could make an awesome one i'm sure.

**Comment by dwhieb** [comment]
Ok finally got a chance to look at this more in depth.

* Go for the `<em>` or `<strong>` tag rather than the `<b>` tag. The `<b>` tag is from the early days of HTML when people weren't being careful about keeping style separate from content. `<b>` is an inherently stylistic tag, whereas `<strong>` and `<em>` are more semantic - they point out text that's "strong" or emphasized, regardless of how you style those. Typically, however, `<em>` will be given italic styling (`font-style: italic;`), and `<strong>` will be given bold styling (`font-weight: bold;`).

* Wug bullets would be great! There's a `list-style-image` property you can use to accomplish that.

* Yeah, `list-style: none;` removes all list-style-types, images, etc. The thing to remember with CSS stylesheets is that rules that come *later* in the sheet override rules that come earlier. However, you really should avoid depending on this if at all possible. Instead, the better thing is to use classes. Here's one sketch of how you might do it:
```
// The HTML
<ul class=wuglist>
  <li>First list item</li>
  <li>Second list item</li>
  <li>Third list item</li>
</ul>

<ul class=regularList>
  <li>First list item</li>
  <li>Second list item</li>
  <li>Third list item</li>
</ul>

// The CSS
.wuglist {
  list-style-image: url(wugbot.svg);
}

.regularList {
  list-style-type: disc;
 }
```

Notice that we *don't* need a third CSS rule with a class like `.noStyleList`, because the CSS reset already does that by default. So lists will be completely unstyled unless you add a class to the `<ul>` or `<ol>` element.

**Comment by dwhieb** [comment]
I wanna look at the line breaking issue too - can you link me to the branch you're working on?

**Comment by wugology** [comment]
I wasn't using the `<b>` tag, I was just saying I tried several tags (including that one) and none were working. But now that I know you've done a CSS reset, that makes sense (I didn't even know that was a thing you could do). The line skip stuff still doesn't make sense though, but then again I haven't really poured through all the style.css file trying to figure it out.

I actually didn't get a chance to work on this stuff tonight, but whatever I have so far is here: https://github.com/wugology/digitallinguistics.github.io

**Comment by dwhieb** [comment]
Awesome I'll check it out!

I'm positive the line break issue has something to do with what's called flexbox. In fact, it just occurred to me what it might be: try adding a rule `flex-direction: row` to the *parent* of the stuff that's doing line breaks.

Here's the single best guide to flexbox I've seen:
http://css-tricks.com/snippets/css/a-guide-to-flexbox/

We're doing (almost) everything on Wugbot with flexbox rather than the old way sites are done, with block styling. That's the line in the CSS that says `display: flex;`. It changes *every* element to display as a flexible, auto-resizing container rather than a static block you have to specify dimensions for. Then later in the CSS I make a few exceptions for inline things like `<span>`, etc.

**Comment by wugology** [comment]
Okay, so I totally missed this flexbox memo and will have to read up on it tomorrow. Does that mean I should be doing something like 80% instead of 700px for body width?

**Comment by dwhieb** [comment]
There are prolly a hundred little decisions like that we haven't found a way to convey to y'all yet. Some of it is just coding best practices, others are our particular choices. I'm doing my best to get documentation up though (esp. the Coding Practices page on the wiki), and I'll keep doing so.

You can totally use px or whatever measurement you'd like with flexbox - it works with anything. But since we're trying to code for responsive design (i.e. pages that will adjust their sizing and display automatically, regardless of what device its viewed on), percentages do tend to be the safest way to go.

Another useful one is `rem` (as opposed to `em`). rem basically means 'the size of the root font', while em is a size relative to the font size of the current element. rem is super nice because it lets you make consistent measurements anywhere across the page. And because I specified the font height in our CSS reset, everything is guaranteed to be correctly proportional.

Finally there's vh 'view height' and vw 'view width', which are percentages of the browser window's height or width.

Percentages, rem, and vh/vw are pretty much the only ones I use, and are best for responsive design.

**Comment by dwhieb** [comment]
Btw your code for those pages looks awesome so far!

**Comment by amundo** [comment]
@wugology hooray! Great to see you here lighting things up!

**Comment by amundo** [comment]
Removing the bullet points from `<li>`s seems a bit much for the reset. We're going to end up having to add them back in by default all the time… for the `<ol>` element that contains words, for instance, yeah, we want to remove the bullets. But that's an edge case.

**Comment by dwhieb** [comment]
I actually did not once need bullets in my little prototype app. I'm not a huge fan of them visually anyways tho. And that was just the app. Our web pages will of course need them.

Maybe in our app style sheet we strip them out, but our default site wide style sheet we leave them.

**Comment by wugology** [comment]
Did we figure out why bolding a word also causes the word to go on its own line?

Also, I can't get any kind of bullet going on using `list-style-type` or `list-style-image`. 

I've tried everything I can think of, including deleting ol/ul completely from the style.css page.

**Comment by dwhieb** [comment]
Hey Onna! @wugology Do you want to commit the About page you've been working on? I'm working on this a little this weekend and can integrate your page into the site now.

**Comment by wugology** [comment]
I did last week: https://github.com/digitallinguistics/digitallinguistics.github.io/pull/1/files

I haven't worked on it since then. Has the issue with the style.css changed? Also I noted a few other issues, like overlap between "wugbot" and "DLX." This may be something we need to discuss/decide.
