### ISSUE TITLE
Clean up the content of the About Wugbot page

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#17]

**Comment by wugology** [comment]
I haven't been to all the meetings and I'm still trying to learn GitHub. This seems like something I can do, but I don't know how. Where is the code? What needs to be done to it?

On a related note, I think obsessively over-commenting our code will help serve our secondary purpose of teaching people how to code. When you're new to all this, seeing what each line of code does is really helpful.

**Comment by dwhieb** [comment]
You on campus? I'm in the lab if you wanna get together for a bit.

**Comment by dwhieb** [comment]
Great point about commenting. Pat and I talked about it, but we were being selfish and weren't thinking about commenting for educational purposes. I'll add that to our [Coding Practices](https://github.com/digitallinguistics/core/wiki/Coding-Practices).

**Comment by wugology** [comment]
I've been cleaning the content as I'm making the page. Is this okay?

**Comment by dwhieb** [comment]
@amundo I'm assigning this to us to sit down and do together at some point. This may also depend on how strictly we decide to delineate wugbot.org and digitallinguistics.org (or rather, linguistics.ucsb.edu/research/digitallinguistics). If they're two entirely separate sites, the About page will be a little different than if they're both under the dlx page.
