### ISSUE TITLE
semantic ui 

### ISSUE THREAD

**Issue by metasyn** [digitallinguistics/core#21]
what would you think of using semantic-ui ?

I'm all about zero dependencies and stuff but... if we want this to look good, we're going to need a lot more than a few a css files here and there. Or if that was all we had, we'd need to do a lot more.

I think semantic-ui is totally up our alley:

from http://learnsemantic.com/preface/introduction.html:
> The goal of Semantic UI is to narrow the divide between how we create meaning personally, through language, and how we construct meaning for computers.

Right ?

> Many programming languages treat logical and mathematical purity as their primary objectives, often ignoring that most of their human counterparts will never reach a zen like purely computational understanding of phenomenon in concordance with the machines they program.

That's what I'm talking about.

> Semantic UI is built around a very different premise, that the real bottleneck in computer programming are humans, and that the best way to advance the web isn't solely providing better institutions for learning programming, or even making more refined tools for existing programmers, but more importantly removing the technical barriers that separate programmatic meaning from human meaning.

Go humans !

> Writing front end code shouldn't require learning the naming or programming conventions of a particular developer.

Especially if we want this to grow !

> Every component is defined using em and rem so that components can be resized simply on the fly. Want a menu to get smaller on mobile? Simply have its font-size change using a media query.

I think a lot of this is in line with our goals so far ? 

> Instead of using short-hand, or codifying naming conventions, Semantic uses simple, common language for parts of interface elements, and familiar patterns found in natural languages for describing elements.

Yay natural language!

> Instead of giving every possible variation or behavior under the sun, element definitions are designed to be a starting off point. No oversized downloads with optional features you will most likely never use, just the stuff to get you going.

I'm in love ! Maybe you will be too. I've used it before and found it intuitive.

Since we want this whole thing to be
 - useable
 - elegant
 - professional
 - easy to contribute to
 - well designed
 - intuitive to use
 - using a common language of UI found across the web.

Open the menu on the left and poke around; I'd love to hear your thoughts.
http://semantic-ui.com/elements/button.html

**Comment by metasyn** [comment]
@amundo @dwhieb just a thought

**Comment by dwhieb** [comment]
This is really cool, I have to admit. The thing is, our goal with DLX is really to make the learning curve as small as possible, and having to install and learn external libraries is specifically one of the things we said at the outset we'd like to avoid. If we do use external libraries, they should be pure JS, very lightweight, and ideally something we can rewrite ourselves so as to obviate the need for an external library. The goal is for all of our external libraries to be temporary. In the long run, this should make it much easier for people who want to contribute new tools or functionality to the wugbot suite to do so. We want anybody with just some basic knowledge of Javascript to be able to use our API and code for our app.

All that said, I think the principles of semantic ui are great, and it wouldn't be a bad idea at all to incorporate their design principles into our own. As we begin building our wugbot stylesheet (which admittedly will be rather small), this would be a great model to keep in mind.

**Comment by amundo** [comment]
Xander thanks so much for this suggestion. We have plans to articulate some more goals for the project in a page or something, but one thing we want is for the site itself to be an educational tool. Hence the minimalism — we want to be able to point to examples within the markup itself, and so forth. Down the road when we get to fancier deployments we will definitely consider more scalable libraries. 

Thanks!! Keep the great ideas coming!
