### ISSUE TITLE
Can't get web fonts working for mobile

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#27]
The @font-face declaration is working for desktop but not any browser for iOS. Tried using woff, ttf, and svg fonts with no luck. Also made sure to include svg IDs and include a leading forward slash on the file path - two common problems in getting web fonts working on iOS. Neither worked.

The only method I haven't tried yet is this:
http://www.fontsquirrel.com/blog/2010/11/troubleshooting-font-face-problems

This requires setting the MIME type for svg fonts. @amundo can you give this a try to see if it works?

**Comment by dwhieb** [comment]
May also be due to hosting via GitHub pages. Maybe we can try pushing to Wugbot.org and see if that works.

**Comment by amundo** [comment]
Yeah I suspect the MIME type stuff can't be reset on GH pages. It will work on wugbot.org. 

An interim solution would be to use the versions of the fonts on google's servers if the ones in question are there. Or, we could use absolute hrefs that point to wugbot.org and upload them there.

**Comment by dwhieb** [comment]
Yeah I kinda forgot it was hosted on GitHub for a moment lol. So this should resolve itself when we push to wugbot.org. I'll close this for now and reopen it if it comes up again.

**Comment by dwhieb** [comment]
Closing this issue for the time being. Will reopen if the font continues failing to load on mobile once we push to Wugbot.org.
