### ISSUE TITLE
Tokenization from transcript tier

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/core#8]
Our data structure should have two tiers that we encourage all users to use: a transcript tier and a phonemic tier. Sophisticated discourse-functional types will use the transcript tier for a DT2 transcript, while everybody else can think of this as 'the tier where you put punctuation'. Users should be able to specify which characters in that tier should be ignored for the purpose of tokenization, allowing us to automatically generate the phonemic tier based on the transcript tier. For example:

if the ignore list looks like this:

`["‰", "⟦", "⟧", "<", ">", "{", "}", "^", ":", "/"]`

then this transcript:

`‰⟦mama ómwabɔ ákamobétéreria <SWA>^kab:isa</SWA>⟧ ⟦níntágeté góːcha⟧}`

should get automatically tokenized as:

`mama ómwabɔ ákamobétéreria kabisa níntágeté góːcha`

and this data populated into the Phonemic tier.

It's possible we might want to develop this as a standalone tool before we integrate it, which makes it a tools idea rather than a feature request.

**Comment by dwhieb** [comment]
WHY AREN'T ISSUES UNICODE COMPLIANT GAH!!!

**Comment by dwhieb** [comment]
The creation of the Tokenizer function in the introdemo closes this issue.

**Comment by amundo** [comment]
Out of curiosity what was the Unicode messup here?

**Comment by dwhieb** [comment]
I couldn't get Unicode to display in the github issue

**Comment by amundo** [comment]
Also, why `transcript` over `transcription`? To me a transcript suggests a series.

**Comment by dwhieb** [comment]
My thinking:

Transcription = purely phonemic representation
Transcript = representation including prosodic features, or syntactic ones (e.g. sentence and phrase punctuation), or anything above the word/phoneme level.

You could have multiple transcripts. Maybe one that's the literary transcript (commas and periods and capital letters), another that's a DT transcript, etc.

Thoughts?

**Comment by dwhieb** [comment]
In general, linguists will probably think of transcript as the tier with punctuation, and transcription as the phonemic tier

**Comment by amundo** [comment]
Oh I see now -- actually I think it's iOctocat (I'm ising it too) that's not supporting unicode. GitHub itself seems pretty solid.
